[package]
name = "rigid_body"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.32.2"
tobj = "3.2.4"
tqdm = "0.4.4"
